Update backup2ipfs

diff --git a/backup2ipfs b/backup2ipfs
--- a/backup2ipfs
+++ b/backup2ipfs
@@ -7,7 +7,7 @@ mode=$1
 
 if [ "$mode" == "" ];
 then
-	mode="--help"
+	mode="--copy"
 fi
 
 
@@ -41,16 +41,18 @@ then
 	for item in $(find -mindepth 1 -maxdepth 1 -not -type l)
 	do
 		echo $item
-		ID=$(ipfs add -rw "$item"| tail -n1 | cut -d ' ' -f 2)
-		echo $ID
+		ID=$(ipfs add -rw "$item" 2>/dev/null| tail -n1 | cut -d ' ' -f 2)
 		if [ "$ID" != "" ];
 		then
+			echo "done"
 			if [ "$mode" == "--move" ];
 			then
 				rm -rf "$item"
 			fi
 			urls=$(echo -e "$urls\n$ID/$item")
 			echo "$ID/$item" >> ipfs-urls.txt
+		else
+			echo "error"
 		fi
 	done
 fi
@@ -62,17 +64,19 @@ then
 	# symb links
 	for allIDs in $(cat ipfs-urls.txt);
 	do
-		cp -vans "/ipfs/$allIDs" ./ 2>/dev/null
-		if [ "$mode" == "--copy" ];
-		then
-			find -type l -print -exec cp "{}" "{}.tmp" \; -exec mv "{}.tmp" "{}" \; 2>/dev/null
-		fi
+		echo $allIDs
+		cp -vans "/ipfs/$allIDs" ./  >/dev/null || exit 1
 	done
+	if [ "$mode" == "--copy" ] || [ "$mode" == "--rebuild" ];
+	then
+		echo "haha"
+		find -type l -print -exec cp "{}" "{}.tmp" \; -exec mv "{}.tmp" "{}" \;  2>/dev/null
+	fi
 else
 	for data in $(cat ipfs-urls.txt | cut -d ";" -f1 | grep Qm | sed "s/\\\"//g");
 	do
         	echo $data;
-	        ipfs pin add --progress $data
+	        ipfs pin add --progress $data || exit 1
 	done
 fi
 
